[formatting]
line_length = 79

[language_servers.pylsp]
enable_pylint = false
enable_mypy = true
enable_pydocstyle = false
enable_ruff = true
enabled = true
enable_pyflakes = false
enable_flake8 = false

[completion]
copilot = false
activate_on_typing = true

[keymap]
preset = "vim"
[keymap.overrides]
"cell.createAbove" = "Ctrl-Shift-arrowup"
"cell.createBelow" = "Ctrl-Shift-arrowdown"

[snippets]
custom_paths = []
include_default_snippets = true

[runtime]
output_max_bytes = 8000000
on_cell_change = "autorun"
pythonpath = []
std_stream_max_bytes = 1000000
auto_instantiate = false
auto_reload = "autorun"
watcher_on_save = "lazy"

[display]
theme = "dark"
dataframes = "rich"
default_width = "full"
cell_output = "below"
code_editor_font_size = 12

[experimental]

[package_management]
manager = "uv"

[ai]
rules = ""

[ai.google]

[ai.open_ai]

[ai.anthropic]

[server]
follow_symlink = false
browser = "default"

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"
